### ISSUE TITLE
Can't deploy to heroku: App not compatible with buildpack

### ISSUE THREAD

**Issue by IvanDerlich** [IvanDerlich/Fakebook#4]
`git push heroku master`

Throws this error. 

![Screenshot from 2020-01-14 20-58-15](https://user-images.githubusercontent.com/5816027/72393099-a1b1a600-3710-11ea-94b3-334b43d9cb1b.png)

So then we try to resolve this buildpack issue running:

`heroku create --buildpack https://github.com/heroku/heroku-buildpack-ruby.git`

`git push heroku master`

But the same error persists.

[This](https://github.com/IvanDerlich/Fakebook/blob/f96e805ff0aa332c21d4fb52d6323cb8533f82b0/Gemfile.lock#L1) is our Gemfile.lock
[This](https://github.com/IvanDerlich/Fakebook/blob/f96e805ff0aa332c21d4fb52d6323cb8533f82b0/Gemfile#L1) is our Gemfile

Edit after answer:
We've tried
`heroku buildpacks:add heroku/ruby`
And we got
` ›   Error: The buildpack heroku/ruby is already set on your app.`

**Comment by IvanDerlich** [comment]
The repository is initialized in the root folder.

**Comment by rsundar** [comment]
Can you list all of your buildpacks with ```$heroku buildpacks```,

This error is mostly due to an incompatible version of the buildpack.

**Comment by IvanDerlich** [comment]
Thanks for your answer!
We type:
`$ heroku buildpacks`
And we get:
`heroku/ruby`

**Comment by rsundar** [comment]
Can you post the output of $heroku logs here.

**Comment by IvanDerlich** [comment]
![Screenshot from 2020-01-15 20-05-37](https://user-images.githubusercontent.com/5816027/72479196-8313e380-37d2-11ea-8a3d-77b27d2dee08.png)

**Comment by rsundar** [comment]
I think your best bet is to destroy that heroku instance and start over, just run ```#heroku buildpacks:add heroku/ruby``` in the very beginning after you run ```$heroku create```.

**Comment by IvanDerlich** [comment]
We solved it!
The cause was that we were trying to deploy from a feature branch and heroku was extracting files from the master branch.
So the solution was to specify to heroku from where to extract the files by using this command
`git push heroku [feature-branch]:master`
